### ISSUE TITLE
No experiments 

### ISSUE THREAD

**Issue by klyrr** [corthmann/eeny-meeny#9]
When the file `experiments.yml` doesn't have any content aka no current experiments the start fails with:

```
[server] ~/.rvm/gems/ruby-2.4.5/gems/eeny-meeny-2.2.1/lib/eeny-meeny/models/experiment.rb:13:in `find_all': undefined method `map' for false:FalseClass (NoMethodError)
[server] Did you mean?  tap
```

**Comment by corthmann** [comment]
Thank you for reporting this issue @klyrr :heart: 

I've fixed the issue and have released a new version (`2.2.2`) which contains the fix.

The fix for your issue can be found in this PR: https://github.com/corthmann/eeny-meeny/pull/10
